// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Jun 14 15:54:35 2022

clk_div clk_div_inst
(
	.clk_in(clk_in_sig) ,	// input  clk_in_sig
	.div_num(div_num_sig) ,	// input  div_num_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.clk_out(clk_out_sig) 	// output  clk_out_sig
);

