// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Fri May 06 18:09:32 2022

TriPhase TriPhase_inst
(
	.CLK_50M(CLK_50M_sig) ,	// input  CLK_50M_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.ADDR(ADDR_sig) ,	// input [11:0] ADDR_sig
	.RD(RD_sig) ,	// input  RD_sig
	.WR(WR_sig) ,	// input  WR_sig
	.DATA(DATA_sig) ,	// inout [15:0] DATA_sig
	.KEY_H(KEY_H_sig) ,	// inout [3:0] KEY_H_sig
	.KEY_V(KEY_V_sig) 	// inout [3:0] KEY_V_sig
);

